# Generated by Django 5.0.2 on 2024-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_thumnail_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
